Adiciona Tratamento Para Secret File
nxcd/niffler pull request #5
Opened 2020-11-18 18:32 UTC by amandaOliveiraSC

# Secret File

A construção da pipeline (CI/CD) para o Nextid demandou a implementação deste PR.

Pois usaremos o recurso de _secret_ do docker para compartilhar informações sigilosas entre o Niffler e o Nextid.

--- 

## Testes

Este PR foi implementado, porém não foi testado.

Será testado após a completa execução da pipeline do Nextid.

---

Essa versão do Niffler será usada, por enquanto, apenas pela versão do NextId no ambiente da RTM, uma *produção* experimental com CI/CD.

2020-11-18 18:59 UTC, caioDelgado requested changes

2020-11-18 18:59 UTC, caioDelgado commented on src/app-config.ts
> +import fs from 'fs'
T.O.C.: Coloca essa importação como a primeira pra formar uma escadinha hehe

2020-11-18 18:59 UTC, caioDelgado commented on src/app-config.ts
> +function buildConfigFile () :any {
Formatação:
`function buildConfigFile(): any {`

2020-11-18 18:59 UTC, caioDelgado commented on src/app-config.ts
> +function getEnv (envName:string, defaultValue:any) :any {
Formatação:
`function getEnv (envName: string, defaultValue: any): any {`

2020-11-18 19:13 UTC, amandaOliveiraSC commented on src/app-config.ts
> +function buildConfigFile () :any {
> Formatação:
> `function buildConfigFile(): any {`

O lint do projeto está adicionando o espaço automaticamente.
Acredito que seja o standard ter esse espaço, pois em outros arquivos também aparece, repara nesse aqui (não alterado neste PR):
src/presentation/routes/find.ts
Eu não conheço o padrão do typescript, então não sei se é erro de configuração da minha IDE ou se está ok.

Poderia confirmar para mim?

![Screenshot from 2020-11-18 16-10-01](https://user-images.githubusercontent.com/48690822/99576471-ca519e80-29b8-11eb-9e7b-5576e49b5be1.png)

2020-11-18 19:14 UTC, amandaOliveiraSC commented on src/app-config.ts
> +import fs from 'fs'
Feito!

2020-11-18 19:25 UTC, caioDelgado commented on src/app-config.ts
> +function buildConfigFile () :any {
Aí foi eu mesmo kkkk a crítica era com o `:`
ta certo hehe

2020-11-18 19:28 UTC, amandaOliveiraSC commented on src/app-config.ts
> +function getEnv (envName:string, defaultValue:any) :any {
Boa, corrigido!

2020-11-18 19:30 UTC, amandaOliveiraSC commented on src/app-config.ts
> +function buildConfigFile () :any {
Ah, não eu vi agora o que falou. O "dois pontos"  deveria estar grudado com o parenteses, né?
E ter um espaço entre ele e a palavra **any**.

Confirma?

Corrigi aqui

2020-11-18 19:57 UTC, caioDelgado approved these changes

2021-06-16 14:46 UTC, caioDelgado approved these changes
LGTM

2021-06-16 20:52 UTC, merged